/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlibarary;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
//import librarysystem.ManagerHompage;
//import librarysystem.ManagerHompage;

public class ManagerProfileUpdate extends javax.swing.JFrame {
private int ManagerID;
    /**
     * Creates new form ManagerProfileUpdate
     */
    public ManagerProfileUpdate() {
        initComponents();
    }
    public ManagerProfileUpdate(int ID) {
        initComponents();
        OK.setBorderPainted(false);
        OK.setOpaque(true);
        OK.setBackground(new java.awt.Color(177, 116, 87));
        ManagerID=ID;
        setLocationRelativeTo(null);
         try {
                String db="jdbc:ucanaccess://DB\\DatabaseFinal.accdb";
                Connection con=DriverManager.getConnection(db);
             
             PreparedStatement pstmt = con.prepareStatement("SELECT * FROM Users Where UserID=? and UserType=?");
             
            pstmt.setInt(1, ManagerID);
            pstmt.setString(2,"Manager");
            ResultSet rs = pstmt.executeQuery();  
            con.close();
            while (rs.next()) {
                String name = rs.getString("Username");
                String email = rs.getString("ContactInfo");   
                String pass=rs.getString("Password");
               Username.setText(name);
               Email.setText(email);
               Password.setText(pass);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error in reading Data");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Eye = new javax.swing.JButton();
        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Info");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("User name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibarary/Images/eye.jpg"))); // NOI18N
        Eye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EyeActionPerformed(evt);
            }
        });

        OK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                        .addComponent(Username))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Eye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eye, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EyeActionPerformed
        // TODO add your handling code here:
         char viewType = Password.getEchoChar();
         if(viewType=='\u25cf'){
             Password.setEchoChar((char) 0);
         }else{
             Password.setEchoChar('\u25cf');
         }
    }//GEN-LAST:event_EyeActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        // check username, email is not repeated
        if(Username.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Please Write a username");
            return;
        }
         if(Email.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Please Write an Emil");
            return;
        }else{
             String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
     
                Pattern pattern = Pattern.compile(emailRegex);
                

             Matcher matcher = pattern.matcher(Email.getText());
            if(!matcher.matches()){
                JOptionPane.showMessageDialog(this, "Enter a valid Email");
                return;
            }
         }
         if(Password.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Enter a valid Password");
            return;
        }
         // check if username already exist
          try {
                String db="jdbc:ucanaccess://DB\\DatabaseFinal.accdb";
                Connection con=DriverManager.getConnection(db);
             
             PreparedStatement pstmt = con.prepareStatement("SELECT * FROM Users Where Username=? and UserID!=?");
             
            
            pstmt.setString(1,Username.getText());
            pstmt.setInt(2, ManagerID);
            ResultSet rs = pstmt.executeQuery();  
            con.close();
            int duplicate=0;
            while (rs.next()) {
                duplicate++;
            }
            if(duplicate>0){
                JOptionPane.showMessageDialog(this, "Username Already Exist, Choose another one");
                return;
            }
            // update database
            try {
                
                
                Connection con2=DriverManager.getConnection(db);
                String UpdateQuery="Update Users set Username=?, ContactInfo=?, Password=? where UserID=?";                  
                    PreparedStatement PS=con2.prepareStatement(UpdateQuery);
                    
                    PS.setString(1, Username.getText());
                    PS.setString(2, Email.getText());
                    PS.setString(3, Password.getText());                  
                    PS.setInt(4, ManagerID);
                    PS.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane,"Information Updated Successfully");
                    con2.close();
                    dispose();
                    
                    String username=DataOperation.GetUsername(ManagerID);
                    new HomePageManager(username).setVisible(true);
              
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error in reading Data");
            }
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error in reading Data");
            
        }
         
         
         
    }//GEN-LAST:event_OKActionPerformed

     
     
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManagerProfileUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManagerProfileUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManagerProfileUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManagerProfileUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManagerProfileUpdate().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JButton Eye;
    private javax.swing.JButton OK;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
