/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlibarary;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.Year;
import javax.swing.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
//import projectlibarary.SearchBooks2;
//import projectlibarary.SearchBooks3;

/**
 *
 * @author shenz
 */
public class SearchBooks1 extends javax.swing.JFrame {
    Connection con;
    ArrayList<String> searchresults = new ArrayList<>();
    private int userId;
    String loggedInUser;
    /**
     * Creates new form NewJFrame
     */
    public SearchBooks1(String loggedInUser,int userId) {
        this.userId = userId;
        this.loggedInUser = loggedInUser;
        
        initComponents();
         try {
            String driverPath = "net.ucanaccess.jdbc.UcanaccessDriver";
            Class.forName(driverPath);
            String PathToDatabase = "DB\\DatabaseFinal.accdb";
            String url = "jdbc:ucanaccess://" + PathToDatabase;
            con = DriverManager.getConnection(url);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchBooks1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Database connection failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.setLocationRelativeTo(null);
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1_search = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton2_search = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1070, 590));

        jPanel1.setBackground(new java.awt.Color(250, 247, 240));
        jPanel1.setMinimumSize(new java.awt.Dimension(1070, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(74, 73, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(229, 226, 226));
        jLabel10.setText("@All rights belong to Iqraa Library");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibarary/Images/logo1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 590));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Search Books By:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jComboBox1_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Author", "Genre", "PublicationDate" }));
        jComboBox1_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_searchActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 160, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 290, 30));

        jButton2_search.setBackground(new java.awt.Color(177, 116, 87));
        jButton2_search.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_search.setText("search");
        jButton2_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_searchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "newest", "oldest" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 90, 30));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 380, 190));

        jButton1.setBackground(new java.awt.Color(250, 247, 240));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibarary/Images/arrow (2).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_searchActionPerformed
        
       String searchText = jTextField1.getText().toLowerCase();
       String selecteditem = (String)jComboBox1_search.getSelectedItem();
       
        String query = "SELECT * FROM [Books Data] WHERE "+selecteditem.toLowerCase()+" LIKE ?";
           try(PreparedStatement stmt = con.prepareStatement(query)){
               stmt.setString(1, "%"+searchText+"%");
               try(ResultSet rs = stmt.executeQuery()){
                   SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");//date format
                   while(rs.next()){
                       String title = rs.getString("Title");
                       java.sql.Date pubDate = rs.getDate("PublicationDate");
                       String formatting = (pubDate != null) ? dateformat.format(pubDate) : "N/A";
                       searchresults.add(title+" ("+formatting+")");
                   }
               }
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
           if (searchresults.isEmpty()){
           JOptionPane.showMessageDialog(this, "Book not found!","Search Reasults", JOptionPane.INFORMATION_MESSAGE);
       }else{
           jList1.setListData(searchresults.toArray(new String[0]));
                  }
    }//GEN-LAST:event_jButton2_searchActionPerformed

    private void jComboBox1_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_searchActionPerformed
        // go to genre frame
        String selecteditem = (String)jComboBox1_search.getSelectedItem();
        if(selecteditem.equals("Genre")){
            SearchBooks2 s = new SearchBooks2(loggedInUser, userId);
            s.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jComboBox1_searchActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // double click on the title to view info page
        if (evt.getClickCount() == 2) {
        String selectedBook = jList1.getSelectedValue();
        if (selectedBook != null && !selectedBook.isEmpty()) {
            String bookTitle = selectedBook.split("\\(")[0].trim();
            SearchBooks3 sb3 = new SearchBooks3(loggedInUser, userId,bookTitle);
            sb3.setVisible(true);
            this.dispose();
        }}
    }//GEN-LAST:event_jList1MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String selectedFilter = (String) jComboBox2.getSelectedItem();
    ArrayList<String> filteredResults = new ArrayList<>();

    int currentYear = Year.now().getValue();
    for (String book : searchresults) {
        try {
            // take publication date part 
            String[] parts = book.split("\\(");
            String dateStr = parts[1].replace(")", "").trim();
            //take the year from the date string
            int year = Integer.parseInt(dateStr.split("-")[0]);
            // Apply the filter based on the year
            if ("newest".equalsIgnoreCase(selectedFilter) && year >= currentYear - 5) {
                filteredResults.add(book);
            } else if ("oldest".equalsIgnoreCase(selectedFilter) && year < currentYear - 5) {
                filteredResults.add(book);
            }
        } catch (Exception e) {
            System.out.println("Error processing book entry: " + book + " | " + e.getMessage());
        }
    }
    if(filteredResults.isEmpty()){
        JOptionPane.showMessageDialog(this, "No books match the filter.", "Filter Results", JOptionPane.INFORMATION_MESSAGE);
    }
    jList1.setListData(filteredResults.toArray(new String[0]));
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new HomePageUser(loggedInUser).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /*
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBooks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBooks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBooks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBooks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBooks1(1).setVisible(true);
            }
        });*/
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2_search;
    private javax.swing.JComboBox<String> jComboBox1_search;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
