/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlibarary;

import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
//import projectlibarary.Borrowing;
import projectlibarary.User;

/**
 *
 * @author Hp
 */
public class SearchBooks3 extends javax.swing.JFrame {

    private String BookName;
    Connection con;
    private int BookId;
    private int userId;
    String loggedInUser;
    /**
     * Creates new form SearchBooks3
     */
    public SearchBooks3(String loggedInUser, int userId, String BookName) {
        this.userId = userId;
        this.BookName = BookName;
        this.loggedInUser = loggedInUser;
        initComponents();
        
        if (BookName == null && BookName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No book selected.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            String driverPath = "net.ucanaccess.jdbc.UcanaccessDriver";
            Class.forName(driverPath);
            String PathToDatabase = "DB\\DatabaseFinal.accdb";
            String url = "jdbc:ucanaccess://" + PathToDatabase;
            con = DriverManager.getConnection(url);
            
            loadBookDetails();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchBooks3.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Database connection failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        this.setLocationRelativeTo(null);
    }
    
    private void loadBookDetails(){
        String query = "SELECT * FROM [Books Data] WHERE Title = ?";
        try(PreparedStatement stmt = con.prepareStatement(query);){ 
            stmt.setString(1, BookName);
            try(ResultSet rs = stmt.executeQuery()){
                if(rs.next()){
                   jTextField1_name.setText(rs.getString("Title"));
                   jTextField2_author.setText(rs.getString("Author"));
                   jTextArea1.setText(rs.getString("Description"));
                   jLabel7CoverTitle.setText(rs.getString("Title"));//add title cover
                   BookId = rs.getInt("BookID");
                   java.sql.Date pubDate = rs.getDate("PublicationDate");
                   if(pubDate != null){
                       String formatDate = new SimpleDateFormat("yyy-MM-dd").format(pubDate);
                       jTextField3_pubDate.setText(formatDate);
                   }
                   //make the description in multi line
                   jTextArea1.setLineWrap(true);//ينقز سطر اذا وصل لنهاية التكست
                   jTextArea1.setWrapStyleWord(true);//يتأكد ان الكلمات ما تنقطع اذا نقز سطر
                   
                   jTextField1_name.setEditable(false);
                   jTextField2_author.setEditable(false);
                   jTextField3_pubDate.setEditable(false);
                   jTextArea1.setEditable(false);
                   //book state 
                   String state = rs.getString("Availability");
                   jLabel6_state.setText(state);
                   jLabel6_state.setForeground("Available".equalsIgnoreCase(state) ? Color.GREEN : Color.RED);
                   if(state.equals("Checked Out")){
                        jButton2_borrow.setEnabled(false);
                   }
                }
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error loading book details "+ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6_state = new javax.swing.JLabel();
        jButton2_borrow = new javax.swing.JButton();
        jTextField1_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2_author = new javax.swing.JTextField();
        jTextField3_pubDate = new javax.swing.JTextField();
        jLabel7CoverTitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 247, 240));
        jPanel1.setMinimumSize(new java.awt.Dimension(1070, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(74, 73, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(229, 226, 226));
        jLabel10.setText("@All rights belong to Iqraa Library");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibarary/Images/logo1.jpg"))); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 590));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Author:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Publication Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Description:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("State:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));

        jLabel6_state.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6_state.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6_state.setText("Available");
        jPanel1.add(jLabel6_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, -1));

        jButton2_borrow.setBackground(new java.awt.Color(177, 116, 87));
        jButton2_borrow.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2_borrow.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_borrow.setText("Borrow");
        jButton2_borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_borrowActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));
        jPanel1.add(jTextField1_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 260, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 490, 100));
        jPanel1.add(jTextField2_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 260, -1));
        jPanel1.add(jTextField3_pubDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 280, -1));

        jLabel7CoverTitle.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        jLabel7CoverTitle.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7CoverTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7CoverTitle.setText("\n");
        jPanel1.add(jLabel7CoverTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 190, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibarary/Images/BookCover22.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 220, 310));

        jButton1.setBackground(new java.awt.Color(250, 247, 240));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibarary/Images/arrow (2).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_borrowActionPerformed
        //int userId = getUserID();//current user id 
        String title = jTextField1_name.getText();
        if(!checkOverdueBooks(userId)){//cheack if user have overdue books
            if(con == null){
                JOptionPane.showMessageDialog(this, "Database connection is not initialized!!","Error Database",JOptionPane.ERROR_MESSAGE);
            }
        Borrowing b = new Borrowing(this,userId,BookId,title);
        b.setVisible(true);
        }
    }//GEN-LAST:event_jButton2_borrowActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new SearchBooks2(loggedInUser,userId).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

private boolean checkOverdueBooks(int userId) {
    String query = "SELECT * FROM [Borrowing Data] WHERE UserID = ?";
    try (PreparedStatement stmt = con.prepareStatement(query)) {
        stmt.setInt(1, userId);
        try (ResultSet rs = stmt.executeQuery()) {
//            if(!rs.next()){
//                System.out.println("No overdue books found!");
//            }
            if (rs.next()) {
                String status = rs.getString("ReturnStatus");
                String status_2 = rs.getString("ReturnDate");
                
                if(status.equals("Late")&& status_2.equals("")){
                JOptionPane.showMessageDialog(this, "You have overdue books.\nBorrowing is not allowed.", "Overdue Books", JOptionPane.WARNING_MESSAGE);
                jButton2_borrow.setEnabled(false);
                return true;
                }
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error checking overdue books: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    return false;
}
public void updateStatus(String state){//update book status (call the method in borrowing class)
    jLabel6_state.setText(state);
    jLabel6_state.setForeground(Color.red);
    jButton2_borrow.setEnabled(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBooks3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBooks3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBooks3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBooks3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBooks3(1,"", "").setVisible(true);
            }
        });*/
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2_borrow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6_state;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7CoverTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1_name;
    private javax.swing.JTextField jTextField2_author;
    private javax.swing.JTextField jTextField3_pubDate;
    // End of variables declaration//GEN-END:variables
}
